### ISSUE TITLE
Does it support using MODX as an IDP?

### ISSUE THREAD

**Issue by bwente** [electrickite/shibboleth#2]
I would like to have user accounts managed in MODX and once logged in to SSO them to another php based platform.

**Comment by electrickite** [comment]
Not currently. I believe this is out of scope for the shibboleth extra. It is intended to be an integration between MODX and a Shibboleth SP, not a full SAML implementation.

One way to achieve this would be to install a stand-alone Shibboleth IdP and use MODX as the user database, through LDAP or a similar protocol. However, none of that would involve this extra.
