### ISSUE TITLE
Shibboleth IdP V3?

### ISSUE THREAD

**Issue by calbear47** [electrickite/shibboleth#3]
Hi there,

I'm just digging my hands into shibboleth and trying to understand how it works, thus I still don't know what I don't know. I'm trying to follow this [guide here](https://docs.google.com/document/d/159AYfb3NCUQ0FWF_MK8mvg1j2vraicXjyjOLH835twA/edit?usp=sharing), but it does require Shibboleth IdP V3? Does this Modx extension support IdP V3? I appreciate your input!

**Comment by electrickite** [comment]
This extra is really just a wrapper around the Shibboleth Service Provider. The majority of your configuration and setup will happen in the SP and your IdP. The SP provides shibboleth attributes for an authenticated user in the PHP environment, which the extra detects and uses to authenticate MODX user accounts.

It should work with IdP v3, sicne there is very little involvement between the extra and the IdP, but if you have problems please feel free to report.

**Comment by calbear47** [comment]
Thank you @electrickite for your direction. I'll let you know if run into any trouble with this extra.
